# Branch Flow Configuration
# Defines the linear order of branches for CI/CD pipeline
# First branch is development, last branch is production

branches:
  - develop    # Development branch (first)
  - main       # Production branch (last)

# Branch roles and behaviors
roles:
  develop:
    creates_pr: true      # Creates PR to next branch
    creates_tags: true    # Creates version tags
    publishes: false      # Does not publish to marketplace
  main:
    creates_pr: false     # Does not create PR (production)
    creates_tags: false   # Does not create tags
    publishes: true       # Publishes to marketplace

# Workflow triggers
triggers:
  versioning: ["develop", "main"]     # Branches that run versioning
  tagging: ["develop"]                # Branches that create tags
  publishing: ["main"]                # Branches that publish
  pr_creation: ["develop"]            # Branches that create PRs
