name: "API Test"

# Simple test workflow for the Node.js Express API
# This demonstrates how to test a backend application in the CI/CD pipeline

on:
  workflow_call:
  workflow_dispatch:

env:
  API_DIR: apps/api
  NODE_VERSION: '22'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.API_DIR }}/package-lock.json

      - name: Install Dependencies
        working-directory: ${{ env.API_DIR }}
        run: npm ci

      - name: Run Tests
        working-directory: ${{ env.API_DIR }}
        run: npm test

      - name: Test API Health (Optional Integration Test)
        working-directory: ${{ env.API_DIR }}
        run: |
          # Start the API in background
          npm start &
          API_PID=$!
          
          # Wait for API to start
          sleep 3
          
          # Simple health check
          curl -f http://localhost:3001/health || exit 1
          
          # Clean up
          kill $API_PID