name: "Changes"

on:
  workflow_call:
    outputs:
      extension: 
        value: ${{ jobs.changes.outputs.extension }}
      cicd:
        value: ${{ jobs.changes.outputs.cicd }}
      
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      extension: ${{ steps.filter.outputs.extension }}
      cicd: ${{ steps.filter.outputs.cicd }}
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          extension:
            - 'src/**'
            - 'package.json'
            - 'tsconfig.json'
            - '*.md'
          cicd: 
            - '.github/workflows/**'
            - '.release-it.cjs'
            - '.releaserc.json'

    - name: Debug Paths Filter Outputs
      run: |
        echo "Extension: ${{ steps.filter.outputs.extension }}"
        echo "CICD: ${{ steps.filter.outputs.cicd }}"