name: "Create PR"

on:
  workflow_call:
    inputs:
      version:
        description: 'The new version to deploy'
        required: true
        type: string
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    # Use branch flow configuration to determine if branch should create PRs
    if: ${{ true }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for version tracking
          
      - name: Check if branch should create PRs
        id: check_pr_creation
        run: |
          CURRENT_BRANCH="${{ github.ref_name }}"
          SHOULD_CREATE_PR=$(.github/scripts/branch-flow.sh has-role "$CURRENT_BRANCH" creates_pr)
          
          if [ "$SHOULD_CREATE_PR" = "true" ]; then
            echo "Branch $CURRENT_BRANCH should create PRs"
            echo "should_create=true" >> $GITHUB_OUTPUT
          else
            echo "Branch $CURRENT_BRANCH should not create PRs"
            echo "should_create=false" >> $GITHUB_OUTPUT
            exit 0  # Exit successfully but skip PR creation
          fi

      - name: Set Up Git
        if: ${{ steps.check_pr_creation.outputs.should_create == 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine Base and Target Version
        if: ${{ steps.check_pr_creation.outputs.should_create == 'true' }}
        id: versioning
        run: |
          set -x
          # Use branch flow configuration to determine next branch
          CURRENT_BRANCH="${{ github.ref_name }}"
          BASE_BRANCH=$(.github/scripts/branch-flow.sh next "$CURRENT_BRANCH")
          
          if [ -z "$BASE_BRANCH" ]; then
            echo "Error: No next branch found for $CURRENT_BRANCH (likely at end of flow)"
            exit 1
          fi
          
          echo "Current branch: $CURRENT_BRANCH"
          echo "Target branch: $BASE_BRANCH"
          
          # Fetch latest tag on base branch
          # Get the current commit hash on the base branch (main)
          BASE_COMMIT_HASH=$(git rev-parse origin/$BASE_BRANCH)

          # Get the tags that are on or before the base commit
          PREV_VERSION=$(git tag --list 'v[0-9]*.[0-9]*.[0-9]*' --sort=-v:refname | while read tag; do git merge-base --is-ancestor "$tag" "$BASE_COMMIT_HASH" && echo "$tag" && break; done)

          if [[ -z "$PREV_VERSION" ]]; then
            echo "No previous version found, aborting."
            exit 1
          fi

          echo "Previous version: $PREV_VERSION"
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
          echo "PREV_VERSION=$PREV_VERSION" >> $GITHUB_ENV

      - name: Create Fake Branches
        run: |
          NEW_BRANCH="temp-${BASE_BRANCH}-${{ inputs.version }}"
          OLD_BRANCH="temp-${BASE_BRANCH}-${PREV_VERSION}"

          # Fetch the latest changes
          git fetch origin

          # Create a new fake branch from the current version of develop (or base branch)
          git checkout -b $NEW_BRANCH origin/${{ github.ref_name }}
          git push origin $NEW_BRANCH --force

          # Create an old branch based on the previous version on the base branch (test or main)
          git checkout -b $OLD_BRANCH origin/$BASE_BRANCH
          git push origin $OLD_BRANCH --force

          echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV
          echo "OLD_BRANCH=$OLD_BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const base = process.env.OLD_BRANCH;
            const head = process.env.NEW_BRANCH;
            const version = '${{ inputs.version }}';

            const { data: existingPRs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: head,
              base: base,
              state: 'open'
            });

            if (existingPRs.length > 0) {
              console.log('A pull request already exists.');
            } else {
              const { data: pullRequest } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `ci: Promote ${process.env.BASE_BRANCH} from ${process.env.PREV_VERSION} to ${version}`,
                head: head,
                base: base,
                body: 'This PR is automatically created by CI.'
              });
              console.log(`Created pull request: ${pullRequest.html_url}`);
            }