name: "Changes"

on:
  workflow_call:
    outputs:
      extension: 
        value: ${{ jobs.changes.outputs.extension }}
      cicd:
        value: ${{ jobs.changes.outputs.cicd }}
      
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      extension: ${{ steps.filter.outputs.extension }}
      cicd: ${{ steps.filter.outputs.cicd }}
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get last tag
      id: last-tag
      run: |
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        if [ -z "$LAST_TAG" ]; then
          echo "No tags found, using HEAD~1 as base"
          echo "base=HEAD~1" >> $GITHUB_OUTPUT
        else
          echo "Last tag: $LAST_TAG"
          echo "base=$LAST_TAG" >> $GITHUB_OUTPUT
        fi

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ steps.last-tag.outputs.base }}
        filters: |
          extension:
            - 'src/**'
            - 'package.json'
            - 'tsconfig.json'
            - '*.md'
          cicd: 
            - '.github/workflows/**'
            - '.release-it.cjs'
            - '.releaserc.json'

    - name: Debug Paths Filter Outputs
      run: |
        echo "Extension: ${{ steps.filter.outputs.extension }}"
        echo "CICD: ${{ steps.filter.outputs.cicd }}"