name: "Branch Configuration"

# Centralized branch configuration for the CI/CD pipeline
# This workflow provides branch arrays that other workflows can use
# instead of hardcoded branch conditions

on:
  workflow_call:
    outputs:
      deployment_branches:
        description: "JSON array of branches that trigger deployments"
        value: ${{ jobs.config.outputs.deployment_branches }}
      version_branches:
        description: "JSON array of branches that generate versions"  
        value: ${{ jobs.config.outputs.version_branches }}
      pr_creation_branches:
        description: "JSON array of branches that create promotion PRs"
        value: ${{ jobs.config.outputs.pr_creation_branches }}

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      deployment_branches: ${{ steps.set-config.outputs.deployment_branches }}
      version_branches: ${{ steps.set-config.outputs.version_branches }}
      pr_creation_branches: ${{ steps.set-config.outputs.pr_creation_branches }}
    steps:
      - name: Set Branch Configuration
        id: set-config
        run: |
          # Define branch arrays as JSON for easy consumption
          echo 'deployment_branches=["develop", "test", "staging", "main"]' >> $GITHUB_OUTPUT
          echo 'version_branches=["develop", "test", "staging", "main"]' >> $GITHUB_OUTPUT  
          echo 'pr_creation_branches=["develop", "test", "staging"]' >> $GITHUB_OUTPUT
          
          echo "📋 Branch configuration set:"
          echo "  Deployment branches: develop, test, staging, main"
          echo "  Version branches: develop, test, staging, main" 
          echo "  PR creation branches: develop, test, staging"

