###############################################################################
# SQUASH COMMIT MESSAGE ENFORCEMENT JOB
###############################################################################
#
# This job enforces that merged PRs use the PR title as the squash commit message.
# It ensures clean commit history by validating merge commit messages.
#
# USAGE:
#   - Runs automatically when PRs are merged
#   - Validates that squash commit message matches PR title
#   - Creates comments for guidance if validation fails
#
# VALIDATION RULES:
#   - Only runs on merged PRs (not closed without merge)
#   - Checks that merge commit message matches PR title
#   - Provides feedback if commit message doesn't match
#
# FEATURES:
#   - Automatic validation on PR merge
#   - Helpful feedback for commit message mismatches
#   - Non-blocking (warnings only, doesn't prevent merge)
#   - Supports both direct calls and PR event triggers
#
###############################################################################

name: Enforce PR Title as Commit Message

on:
  pull_request:
    types: [closed]
  workflow_call:

jobs:
  enforce-squash-message:
    if: github.event.pull_request.merged == true && github.event.pull_request.merge_commit_sha != null
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check squash commit message
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          SHA="${{ github.event.pull_request.merge_commit_sha }}"
          MESSAGE=$(git log -1 --pretty=%B $SHA)

          echo "PR Title: $TITLE"
          echo "Squash Commit Message: $MESSAGE"

          if [[ "$MESSAGE" != "$TITLE" ]]; then
            echo "❌ Commit message does not match PR title!"
            exit 1
          fi
