name: "Docs:Deploy"


on:
  workflow_dispatch:
  workflow_call: 

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
  
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter @madi/docs
    
      - name: Build website
        working-directory: ./apps/docs
        run: pnpm run build
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: ./apps/docs/build
