name: "PR Title Check"

on:
  workflow_call:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  pr-title-check:
    name: Check PR Title Format
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title follows conventional commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure types (must match your release-it config)
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
          # Require scope for certain types
          requireScope: false
          # Allow custom scopes
          scopes: |
            extension
            ui
            ai
            config
            cicd
          # Custom subject pattern
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          # Ignore merge commits
          ignoreLabels: |
            ignore-semantic-pull-request
