name: Auto Dependencies Pipeline

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  auto-dependencies:
    uses: ./.github/workflows/job.maintenance.deps.yml
    secrets: inherit
